local CSS = require("mangacenter_css")

describe("MangaCenter CSS", function()
    it("builds a constant signed shift", function()
        local css = CSS.build("constant", 7.5)
        assert.is_truthy(css:find("DocFragment:not%(:first%-child%) > body"))
        assert.is_truthy(css:find("margin%-left: 7%.5vw"))
        assert.is_truthy(css:find("margin%-right: %-7%.5vw"))
    end)

    it("reverses the shift on alternating spine pages", function()
        local css = CSS.build("alternating", -4)
        assert.is_truthy(css:find("nth%-child%(odd%)"))
        assert.is_truthy(css:find("nth%-child%(even%)"))
        assert.is_truthy(css:find("margin%-left: %-4vw"))
        assert.is_truthy(css:find("margin%-left: 4vw"))
    end)

    it("does nothing at zero and clamps extreme values", function()
        assert.are.equal("", CSS.build("constant", 0))
        local css = CSS.build("constant", 100)
        assert.is_truthy(css:find("margin%-left: 25vw"))
    end)
end)
