local Zoom = require("mangacenter_zoom")

describe("MangaCenter continuous controls", function()
    it("scales native page-width zoom", function()
        assert.are.equal(0.8, Zoom.apply(1, 80))
        assert.are.equal(1.5, Zoom.apply(2, 75))
    end)

    it("recognizes width-fitting modes", function()
        assert.is_true(Zoom.isWidthMode("pagewidth"))
        assert.is_true(Zoom.isWidthMode("contentwidth"))
        assert.is_false(Zoom.isWidthMode("page"))
        assert.is_false(Zoom.isWidthMode("manual"))
    end)

    it("clamps width and overlap ranges", function()
        assert.are.equal(50, Zoom.normalizePercent(10))
        assert.are.equal(100, Zoom.normalizePercent(150))
        assert.are.equal(82.5, Zoom.normalizePercent(82.5))
        assert.are.equal(0, Zoom.normalizeOverlapPercent(-5))
        assert.are.equal(90, Zoom.normalizeOverlapPercent(99))
    end)

    it("clamps and applies continuous scroll gesture multipliers", function()
        assert.are.equal(0.25, Zoom.normalizeScrollMultiplier(0.1))
        assert.are.equal(9, Zoom.normalizeScrollMultiplier(9))
        assert.are.equal(10, Zoom.normalizeScrollMultiplier(20))
        assert.are.equal(1, Zoom.normalizeScrollMultiplier(nil))
        assert.are.equal(150, Zoom.applyScrollMultiplier(100, 1.5))
        assert.are.equal(-50, Zoom.applyScrollMultiplier(-100, 0.5))
    end)

    it("converts overlap percentage to pixels", function()
        assert.are.equal(100, Zoom.overlapPixels(10, 1000))
        assert.are.equal(0, Zoom.overlapPixels(0, 1000))
        assert.is_nil(Zoom.overlapPixels(nil, 1000))
    end)
end)
